### ISSUE TITLE
Item ID is not defined

### ISSUE THREAD

**Issue by calebidklol** [Wizz1337/TikTokMassBotting#81]
Traceback (most recent call last): File "main.py", line 139, in <module> itemID = clearURL(VideoURI) File "main.py", line 100, in clearURL UrlParsed = urlparse(r.head(itemID, verify=False, allow_redirects=True, timeout=5).url) NameError: name 'itemID' is not defined

**Comment by ayamkv** [comment]
your link probably looks like this
> https://vt.tiktok.com/xxxxxxxxx/

‎
my current fix is to just
open it on your browser and copy the full link


> https://www.tiktok.com/@account/video/0000000000000000000

**Comment by ayamkv** [comment]
LGTM
